name: CI

on:
  push:
    branches:
      - v*
      - main
  pull_request: {}
  workflow_dispatch: {}

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          submodules: true

      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org

      - name: Run lint
        run: |
          yarn cache clean --all
          YARN_CHECKSUM_BEHAVIOR=update yarn
          yarn
          yarn build
          yarn doc
          yarn lint

  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18]
    env:
      INFURA_KEY: ${{ secrets.INFURA_KEY }}
      DEPLOYER_MNEMONIC: ${{ secrets.DEPLOYER_MNEMONIC }}
      ETHERSCAN_KEY: ${{ secrets.ETHERSCAN_KEY }}
      MOCHA_JOBS: 0
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          submodules: true

      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org

      - name: Run unit tests
        run: |
          yarn cache clean --all
          YARN_CHECKSUM_BEHAVIOR=update yarn
          yarn
          yarn build
          yarn test

  coverage:
    name: Coverage Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18]
    env:
      INFURA_KEY: ${{ secrets.INFURA_KEY }}
      DEPLOYER_MNEMONIC: ${{ secrets.DEPLOYER_MNEMONIC }}
      ETHERSCAN_KEY: ${{ secrets.ETHERSCAN_KEY }}
      REPORT_GAS: true
      MOCHA_JOBS: 0
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          submodules: true
          fetch-depth: 2
      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: |
          yarn cache clean --all
          YARN_CHECKSUM_BEHAVIOR=update yarn
          yarn
          yarn build
          yarn coverage
        env:
          NODE_OPTIONS: --max_old_space_size=8192
      - name: Publish coverage
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info

  fork:
    name: Fork Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18]
        network: [goerli, mainnet]
    env:
      ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
      DEPLOYER_MNEMONIC: ${{ secrets.DEPLOYER_MNEMONIC }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          submodules: true

      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: |
          yarn cache clean --all
          YARN_CHECKSUM_BEHAVIOR=update yarn
          yarn
          yarn build

      - name: Fork ${{ matrix.network }} check
        run: |
          echo NETWORK=localhost >> .env
          echo ALCHEMY_KEY=${{ env.ALCHEMY_KEY }} >> .env
          echo DEPLOYER_MNEMONIC=${{ env.DEPLOYER_MNEMONIC }} >> .env
          echo ETHERSCAN_VERIFICATION=false >> .env
          echo FORK=${{ matrix.network }} >> .env
          make hardhat &
          sleep 60
          make deploy
          pkill node || true
